export default [
  {
    "aliases": [
      "Princess Zelda\r",
      "Sheik\r",
      "Shiek\r",
      "Tetra\r",
      "Queen Zelda\r",
      "Hylia"
    ],
    "analyzed_title": "zelda",
    "background_image_url": "https://static.giantbomb.com/",
    "bundle": "Character",
    "content_type_id": 3005,
    "date": "2017-04-02",
    "date_created": "2008-05-06T23:37:09Z",
    "date_updated": "2017-04-02T12:23:55Z",
    "deck": "Zelda is the titular figure of The Legend of Zelda. She is most often depicted as the princess of Hyrule.",
    "engineId": "giantbomb",
    "engineKey": "cYD2HM4LcaeJSuy57Uqb",
    "gender": "female",
    "id": 5,
    "image_thumbnail_url": "https://static.giantbomb.com/uploads/square_mini/0/26/9876-zelda.jpg",
    "image_url": "https://static.giantbomb.com/uploads/original/0/26/9876-zelda.jpg",
    "index_name": "character",
    "is_important": "false",
    "label": "<span class=\"search-type\">Character</span> linked to <span class=\"search-linked-games\">31 games</span>",
    "name": "Zelda",
    "popularity": 31,
    "publishable": "true",
    "real_name": "",
    "related_games_count": "31 games",
    "slug": "zelda",
    "title": "Zelda",
    "url": "/zelda/3005-5/"
  },
  {
    "aliases": [
      "LoZ",
      "Zelda no Densetsu",
      "ゼルダの伝説"
    ],
    "analyzed_title": "the legend of zelda",
    "background_image_url": "https://static.giantbomb.com/",
    "bundle": "Franchise",
    "content_type_id": 3025,
    "date": "2016-03-26",
    "date_created": "2008-04-08T18:32:29Z",
    "date_updated": "2016-03-27T01:34:25Z",
    "deck": "Nintendo's flagship fantasy action-adventure series created by Shigeru Miyamoto and Takashi Tezuka in 1985, the Zelda series is the source of many revolutionary gameplay conventions, and continues to be one of the most popular and critically acclaimed video game franchises of all time.",
    "engineId": "giantbomb",
    "engineKey": "cYD2HM4LcaeJSuy57Uqb",
    "id": 9,
    "image_thumbnail_url": "https://static.giantbomb.com/uploads/square_mini/9/99864/2389801-zelda_logo.svg.png",
    "image_url": "https://static.giantbomb.com/uploads/original/9/99864/2389801-zelda_logo.svg.png",
    "index_name": "franchise",
    "is_important": "false",
    "label": "<span class=\"search-type\">Franchise</span> linked to <span class=\"search-linked-games\">31 games</span>",
    "name": "The Legend of Zelda",
    "popularity": 31,
    "publishable": "true",
    "related_games_count": "31 games",
    "slug": "the-legend-of-zelda",
    "title": "The Legend of Zelda",
    "url": "/the-legend-of-zelda/3025-9/"
  },
  {
    "aliases": [
      "ゼルダの伝説\r",
      "LoZ\r",
      "Zelda no Densetsu\r",
      "Zelda no Densetsu 1: The Hyrule Fantasy"
    ],
    "analyzed_title": "the legend of zelda",
    "background_image_url": "https://static.giantbomb.com/",
    "bundle": "Game",
    "content_type_id": 3030,
    "date": "2017-02-20",
    "date_created": "2008-04-01T23:01:53Z",
    "date_updated": "2017-02-21T02:39:37Z",
    "deck": "A young boy explores a huge overworld filled with enemies and dungeons to find and rescue Princess Zelda from the evil Ganon.",
    "engineId": "giantbomb",
    "engineKey": "cYD2HM4LcaeJSuy57Uqb",
    "id": 11949,
    "image_thumbnail_url": "https://static.giantbomb.com/uploads/square_mini/0/26/10169-legendofzelda-goldbox.png",
    "image_url": "https://static.giantbomb.com/uploads/original/0/26/10169-legendofzelda-goldbox.png",
    "index_name": "game",
    "is_important": "false",
    "label": "<span class=\"search-type\">Game</span> <span class=\"search-year\">1986</span> <span class=\"search-platform\">(FDS, NES, GBA, WSHP + 1 more)</span>",
    "name": "The Legend of Zelda",
    "platform_short_names": "FDS, NES, GBA, WSHP + 1 more",
    "popularity": 0,
    "publishable": "true",
    "release_date": "1986-02-21T08:00:00Z",
    "release_year": "1986",
    "slug": "the-legend-of-zelda",
    "title": "The Legend of Zelda",
    "url": "/the-legend-of-zelda/3030-11949/"
  },
  {
    "aliases": [
      "The Legend of Zelda Collection"
    ],
    "analyzed_title": "the legend of zelda collectors edition",
    "background_image_url": "https://static.giantbomb.com/",
    "bundle": "Game",
    "content_type_id": 3030,
    "date": "2015-03-05",
    "date_created": "2008-04-01T23:13:05Z",
    "date_updated": "2015-03-06T02:04:05Z",
    "deck": "The Collector's Edition of The Legend of Zelda includes both NES Zelda games, both Nintendo 64 Zelda games, and a demo of The Legend of Zelda: Wind Waker for the Gamecube.",
    "engineId": "giantbomb",
    "engineKey": "cYD2HM4LcaeJSuy57Uqb",
    "id": 14114,
    "image_thumbnail_url": "https://static.giantbomb.com/uploads/square_mini/1/12813/777595-919239_52155_front.jpg",
    "image_url": "https://static.giantbomb.com/uploads/original/1/12813/777595-919239_52155_front.jpg",
    "index_name": "game",
    "is_important": "false",
    "label": "<span class=\"search-type\">Game</span> <span class=\"search-year\">2003</span> <span class=\"search-platform\">(GC)</span>",
    "name": "The Legend of Zelda: Collector's Edition",
    "platform_short_names": "GC",
    "popularity": 0,
    "publishable": "true",
    "release_date": "2003-11-14T08:00:00Z",
    "release_year": "2003",
    "slug": "the-legend-of-zelda-collectors-edition",
    "title": "The Legend of Zelda: Collector's Edition",
    "url": "/the-legend-of-zelda-collectors-edition/3030-14114/"
  },
  {
    "aliases": [
      "Zelda II",
      "Zelda 2: The Adventure of Link",
      "The Legend of Zelda 2: Link no Bouken",
      "The Legend of Zelda 2: Link no Bōken",
      "THE LEGEND OF ZELDA 2 リンクの冒険"
    ],
    "analyzed_title": "zelda ii the adventure of link",
    "background_image_url": "https://static.giantbomb.com/",
    "bundle": "Game",
    "content_type_id": 3030,
    "date": "2016-11-11",
    "date_created": "2008-04-01T23:26:07Z",
    "date_updated": "2016-11-11T17:49:21Z",
    "deck": "Zelda II: The Adventure of Link is the second entry in the ground-breaking Zelda franchise. This controversial follow-up ditches the original's top-down perspective for 2D side-scrolling exploration and combat. The 2D towns, dungeons and combat arenas are tied together by a top-down overworld.",
    "engineId": "giantbomb",
    "engineKey": "cYD2HM4LcaeJSuy57Uqb",
    "id": 16241,
    "image_thumbnail_url": "https://static.giantbomb.com/uploads/square_mini/9/93770/2362640-nes_legendofzeldaadevntureoflink.jpg",
    "image_url": "https://static.giantbomb.com/uploads/original/9/93770/2362640-nes_legendofzeldaadevntureoflink.jpg",
    "index_name": "game",
    "is_important": "false",
    "label": "<span class=\"search-type\">Game</span> <span class=\"search-year\">1987</span> <span class=\"search-platform\">(FDS, NES, GBA, WSHP + 1 more)</span>",
    "name": "Zelda II: The Adventure of Link",
    "platform_short_names": "FDS, NES, GBA, WSHP + 1 more",
    "popularity": 0,
    "publishable": "true",
    "release_date": "1987-01-14T08:00:00Z",
    "release_year": "1987",
    "slug": "zelda-ii-the-adventure-of-link",
    "title": "Zelda II: The Adventure of Link",
    "url": "/zelda-ii-the-adventure-of-link/3030-16241/"
  },
  {
    "aliases": [
      "OOT\r",
      "LOZ:OOT\r",
      "Zelda no Densetsu: Toki no Ocarina\r",
      "ゼルダの伝説 時のオカリナ\r",
      "Zelda 64\r",
      "The Legend of Zelda: Ocarina of Time 3D"
    ],
    "analyzed_title": "the legend of zelda ocarina of time",
    "background_image_url": "https://static.giantbomb.com/",
    "bundle": "Game",
    "content_type_id": 3030,
    "date": "2017-03-31",
    "date_created": "2008-04-01T23:04:56Z",
    "date_updated": "2017-04-01T00:28:30Z",
    "deck": "The first 3D Legend of Zelda game, Ocarina of Time was created for the Nintendo 64 in 1998 and introduced innovative mechanics such as Z-targeting as well as many of the series' other trademarks. It has frequently been ranked as the greatest game of all time by many publications.",
    "engineId": "giantbomb",
    "engineKey": "cYD2HM4LcaeJSuy57Uqb",
    "id": 12572,
    "image_thumbnail_url": "https://static.giantbomb.com/uploads/square_mini/8/87790/2204862-box_tlozoot.png",
    "image_url": "https://static.giantbomb.com/uploads/original/8/87790/2204862-box_tlozoot.png",
    "index_name": "game",
    "is_important": "false",
    "label": "<span class=\"search-type\">Game</span> <span class=\"search-year\">1998</span> <span class=\"search-platform\">(N64, WSHP)</span>",
    "name": "The Legend of Zelda: Ocarina of Time",
    "platform_short_names": "N64, WSHP",
    "popularity": 0,
    "publishable": "true",
    "release_date": "1998-11-21T08:00:00Z",
    "release_year": "1998",
    "slug": "the-legend-of-zelda-ocarina-of-time",
    "title": "The Legend of Zelda: Ocarina of Time",
    "url": "/the-legend-of-zelda-ocarina-of-time/3030-12572/"
  },
  {
    "aliases": [
      "Zelda no Densetsu: Kaze no Takt\r",
      "Zelda no Densetsu: Kaze no Takuto\r",
      "ゼルダの伝説 風のタクト\r",
      "TWW"
    ],
    "analyzed_title": "the legend of zelda the wind waker",
    "background_image_url": "https://static.giantbomb.com/",
    "bundle": "Game",
    "content_type_id": 3030,
    "date": "2016-01-31",
    "date_created": "2008-04-01T23:40:54Z",
    "date_updated": "2016-02-01T01:14:51Z",
    "deck": "The first entry in the Zelda franchise for the GameCube, sporting a distinctive cel-shaded graphics style. It built upon the mechanics of Ocarina of Time and Majora's Mask, and its oceanic setting emphasized exploration.",
    "engineId": "giantbomb",
    "engineKey": "cYD2HM4LcaeJSuy57Uqb",
    "id": 18508,
    "image_thumbnail_url": "https://static.giantbomb.com/uploads/square_mini/8/82063/2609768-lozww.jpg",
    "image_url": "https://static.giantbomb.com/uploads/original/8/82063/2609768-lozww.jpg",
    "index_name": "game",
    "is_important": "false",
    "label": "<span class=\"search-type\">Game</span> <span class=\"search-year\">2002</span> <span class=\"search-platform\">(GC)</span>",
    "name": "The Legend of Zelda: The Wind Waker",
    "platform_short_names": "GC",
    "popularity": 0,
    "publishable": "true",
    "release_date": "2002-12-13T08:00:00Z",
    "release_year": "2002",
    "slug": "the-legend-of-zelda-the-wind-waker",
    "title": "The Legend of Zelda: The Wind Waker",
    "url": "/the-legend-of-zelda-the-wind-waker/3030-18508/"
  },
  {
    "aliases": [
      "Zelda III",
      "LTTP",
      "Zelda no Densetsu: Kamigami no Triforce",
      "ゼルダの伝説 神々のトライフォース"
    ],
    "analyzed_title": "the legend of zelda a link to the past",
    "background_image_url": "https://static.giantbomb.com/",
    "bundle": "Game",
    "content_type_id": 3030,
    "date": "2017-06-17",
    "date_created": "2008-04-01T22:54:14Z",
    "date_updated": "2017-06-18T00:04:24Z",
    "deck": "The third installment in the Zelda series makes a return to the top-down 2D gameplay found in the first game. This time around, Link needs to travel between the light and dark world in order to set things straight in the kingdom of Hyrule.",
    "engineId": "giantbomb",
    "engineKey": "cYD2HM4LcaeJSuy57Uqb",
    "id": 10276,
    "image_thumbnail_url": "https://static.giantbomb.com/uploads/square_mini/8/82063/2831954-legend_of_zelda_3_-_snes_-_album_art.jpg",
    "image_url": "https://static.giantbomb.com/uploads/original/8/82063/2831954-legend_of_zelda_3_-_snes_-_album_art.jpg",
    "index_name": "game",
    "is_important": "false",
    "label": "<span class=\"search-type\">Game</span> <span class=\"search-year\">1991</span> <span class=\"search-platform\">(SNES, WSHP)</span>",
    "name": "The Legend of Zelda: A Link to the Past",
    "platform_short_names": "SNES, WSHP",
    "popularity": 0,
    "publishable": "true",
    "release_date": "1991-11-21T08:00:00Z",
    "release_year": "1991",
    "slug": "the-legend-of-zelda-a-link-to-the-past",
    "title": "The Legend of Zelda: A Link to the Past",
    "url": "/the-legend-of-zelda-a-link-to-the-past/3030-10276/"
  }
]
